project:
  type: website 

# See https://youtu.be/_f3latmOhew?t=1051 for more info on web site creation
website: 
  title: "2023 - MSC - ICA - Quarto Examples"
  navbar: 
    left:
      - 1_Intro_To_Quarto.qmd
      - 2_Interactive_Plots_With_Plotly.qmd
